openapi: 3.0.2
info:
  title: Inheritance test
  version: 1.0.0
paths:
  /sampleA:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseObject'
      responses:
        '200':
          description: success
    get:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseObject'
  /sampleB:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InheritanceSample'
      responses:
        '200':
          description: success
    get:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InheritanceSample'
components:
  schemas:
    BaseObject:
      type: object
      required:
        - foo
      properties:
        foo:
          type: string
      discriminator:
        propertyName: foo

    InheritanceSample:
      allOf:
        - $ref: '#/components/schemas/BaseObject'
        - type: object
          properties:
            bar:
              type: string

servers:
  - url: 'http://localhost:8080'
